[pytest]

markers =
    unit: testes unitários
    integration: testes de integração
    functional: testes funcionais
    regression: testes de regressão
    api: testes da API
    e2e: testes End-to-End
    security: testes de segurança